version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-anhvu
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: todo-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

      #  Ghi đè cấu hình mạng nội bộ của Docker
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db

volumes:
  mysql_data:
